# Generated by Django 5.0.6 on 2024-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "categories_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="categories_id"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "image_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="image_id"
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Images",
            },
        ),
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "location_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="location_id"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Locations",
            },
        ),
    ]
