# Generated by Django 5.0.6 on 2024-05-24 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_alter_listing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"verbose_name_plural": "Listings"},
        ),
    ]
